name: Run MATLAB Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-matlab:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up MATLAB
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run macOS-only command
        if: matrix.os == 'macos-latest'
        run: find /Users/runner/hostedtoolcache/MATLAB/ -name "libMatlabEngine.dylib"

      # Step 3: Build MEX
      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release
      
      - name: Install
        run: cmake --install build --prefix ./

      # Step 4: Run a MATLAB script
      - name: Run MATLAB script
        uses: matlab-actions/run-command@v2
        with:
          command: |
            cd('bin'); 
            run('testSumScalar.m')